pytest_failure_tracker/__init__.py,sha256=m6kyaNpwBcP1XYcqrelX2oS3PJuOnElOcRdBa9pEb8c,22
pytest_failure_tracker/plugin.py,sha256=mMT1ud84Z5J6WyGpUZFPJTLZFbAwdLoqwqEuk-xS-fw,3175
pytest_failure_tracker-0.2.2.dist-info/LICENSE,sha256=kkQNut_S39g9qpI1bIbuw5aoKL9XNLo8NcS2-QP3pWU,1060
pytest_failure_tracker-0.2.2.dist-info/METADATA,sha256=tNTptdWW6j8vHLBl2v7UD5SJm9ZgaWyQR-82UuPopvw,3887
pytest_failure_tracker-0.2.2.dist-info/WHEEL,sha256=Z4pYXqR_rTB7OWNDYFOm1qRk0RX6GFP2o8LgvP453Hk,91
pytest_failure_tracker-0.2.2.dist-info/entry_points.txt,sha256=A55NgfgVi1c5EU9Ot_wElLZKkKJAGrr8XtG9LWllEUg,59
pytest_failure_tracker-0.2.2.dist-info/top_level.txt,sha256=QM3vmr7t0sH3WjTO5pbzwSwnonzZ0zDGXX7OpxMFk_k,23
pytest_failure_tracker-0.2.2.dist-info/RECORD,,
