pytest_failure_tracker/__init__.py,sha256=Zn1KFblwuFHiDRdRAiRnDBRkbPttWh44jKa5zG2ov0E,22
pytest_failure_tracker/plugin.py,sha256=mMT1ud84Z5J6WyGpUZFPJTLZFbAwdLoqwqEuk-xS-fw,3175
pytest_failure_tracker-0.2.0.dist-info/LICENSE,sha256=pWiDBWmgHOAHWHO7oWN9wrGIk5uHsR62OiDffMNGDhM,1068
pytest_failure_tracker-0.2.0.dist-info/METADATA,sha256=oWz4dez8EOr2iwkPa8HnOmFiGM7VIFwPgoERQjNUFnw,3852
pytest_failure_tracker-0.2.0.dist-info/WHEEL,sha256=Z4pYXqR_rTB7OWNDYFOm1qRk0RX6GFP2o8LgvP453Hk,91
pytest_failure_tracker-0.2.0.dist-info/entry_points.txt,sha256=A55NgfgVi1c5EU9Ot_wElLZKkKJAGrr8XtG9LWllEUg,59
pytest_failure_tracker-0.2.0.dist-info/top_level.txt,sha256=QM3vmr7t0sH3WjTO5pbzwSwnonzZ0zDGXX7OpxMFk_k,23
pytest_failure_tracker-0.2.0.dist-info/RECORD,,
